require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/customer/clients", type: :request do

  # This should return the minimal set of attributes required to create a valid
  # Customer::Client. As you add validations to Customer::Client, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    attributes_for(:customer_client)
  }

  let(:invalid_attributes) {
    { name: 1, rent_from: 'invalid date', rent_to: 'invalid date'}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Customer::Client.create! valid_attributes
      get customer_clients_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      client = Customer::Client.create! valid_attributes
      get customer_client_url(client)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_customer_client_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      client = Customer::Client.create! valid_attributes
      get edit_customer_client_url(client)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Customer::Client" do
        expect {
          post customer_clients_url, params: { customer_client: valid_attributes }
        }.to change(Customer::Client, :count).by(1)
      end

      it "redirects to the created customer_client" do
        post customer_clients_url, params: { customer_client: valid_attributes }
        expect(response).to redirect_to(customer_client_url(Customer::Client.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Customer::Client" do
        expect {
          post customer_clients_url, params: { customer_client: invalid_attributes }
        }.to change(Customer::Client, :count).by(0)
      end


      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post customer_clients_url, params: { customer_client: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { name: 'new name' }
      }

      it "updates the requested customer_client" do
        client = Customer::Client.create! valid_attributes
        patch customer_client_url(client), params: { customer_client: new_attributes }
        client.reload
        expect(client.name).to eq 'new name'
      end

      it "redirects to the customer_client" do
        client = Customer::Client.create! valid_attributes
        patch customer_client_url(client), params: { customer_client: new_attributes }
        client.reload
        expect(response).to redirect_to(customer_client_url(client))
      end
    end

    context "with invalid parameters" do

      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        client = Customer::Client.create! valid_attributes
        patch customer_client_url(client), params: { customer_client: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested customer_client" do
      client = Customer::Client.create! valid_attributes
      expect {
        delete customer_client_url(client)
      }.to change(Customer::Client, :count).by(-1)
    end

    it "redirects to the customer_clients list" do
      client = Customer::Client.create! valid_attributes
      delete customer_client_url(client)
      expect(response).to redirect_to(customer_clients_url)
    end
  end
end
